Added checker, preflight and installer scripts for Pixie.
X-CBG/xk8s pull request #17
Opened 2022-12-23 11:42 UTC by noman-xg

**What is this PR about ?**

This pull request adds checker, installer and pre-flight scripts for Pixie. Checker runs a suite of checks to determine the footprint of PIxie in the Kubernetes cluster. Then pre-flight checks kick in to ascertain whether the given environment is compatible with Pixie or not, if yes then installer script will take over and install Pixie components followed by deployment of Pixie to the cluster.

1.     System based checks
2.     Cluster based checks
3.     Pre-flight checks
4.     Installation and Deployment

**System based checks**
 
- [x]  We check for binary used for deployment of pixie i.e. px.

**Cluster based checks**

- [x] We check for different namespaces that are created as part of a pixie deployment eg px, pl, px-operator using kubectl.
- [x] If kubectl is not present on the system we use curl to talk to api server and check for namespaces.
- [x] If namespaces ar

**Pre-flight checks based checks**

- [x] Kubernetes Version Check. Pixie is compatible wirh 1.21+.
- [x] Linux Kernel Version Check. Pixie is compatible wirh 4.14+ 
- [x] CPU architecture type Check. Pixie is compatible with x86_64 only. 
- [x] Minimum memory per node Check. Pixie requires at least 1 Gib of free memory per node.

**What else to be done ?**

_Integration of checker, pre-flight and installer._

> NOTE:

1.  _We are using official pixie installer script (with some changes ) to install PIxie. The changes that i have made are about prompting users with consent message (y/n). Since we don't want to halt script execution mid way to get user input on the backend i have removed such prompts. These prompts will he handled on the product's UI where we can explicitly ask the same questions before beginning the installation procedure._
2.  _During pixie install we have to provide api-key upon request by default on the CLI or through browser auth but we'll have to provide the pre-generated api_key through makefile to `px auth login` to ensure our installation goes through._

2022-12-23 11:49 UTC, sidra-xcbg commented on Makefile
> +PX_API_KEY="px-api-a46a7c6f-390f-4f84-be88-da1b4563971d"
comment on this static assignment being temporary

2022-12-23 11:52 UTC, alikhanxgrid commented
> * [x]  If namespaces ar

In the description you provided this is incomplete.

2022-12-23 11:53 UTC, alikhanxgrid commented on Makefile
> +# Pixie 	==> px
Mis-aligned arrow with the lines below.

2022-12-23 11:56 UTC, alikhanxgrid commented on Makefile
> +KAPI_SERVER = 192.168.50.175:8443
Comment needs to be added if these things would be dynamic down the line.

2022-12-23 12:15 UTC, noman-xg commented on Makefile
> +PX_API_KEY="px-api-a46a7c6f-390f-4f84-be88-da1b4563971d"
fixed in e88adddc99b0f427d210ada3b6fabf29dcc0dc1c

2022-12-23 12:15 UTC, noman-xg commented on Makefile
> +KAPI_SERVER = 192.168.50.175:8443
fixed in e88adddc99b0f427d210ada3b6fabf29dcc0dc1c

2022-12-24 02:25 UTC, abdullah-shah1 requested changes
Looks good structurally, few logical comments.

2022-12-24 02:25 UTC, abdullah-shah1 commented on src/checker/px-checker.sh
> +    mapfile -t plDeploy < <(kubectl get deploy -n pl --no-headers 2> /dev/null | awk '{print $1}')
is mapfile always present ? Maybe better to have all required tools checks done in pre-checker and proceed accordingly

2022-12-24 02:25 UTC, abdullah-shah1 commented on src/checker/px-checker.sh
> +        if [[ $dp == "kelvin" || $dp == "vizier-cloud-connector" || $dp == "vizier-query-broker" ]];
will these values always be these ? should we make them configurable ?

2022-12-24 02:25 UTC, abdullah-shah1 commented on src/installer/px-installer.sh
> +#!/usr/bin/env bash
I assume this is official pixie installer script, is it possible to just redirect and get the latest script at runtime (or a particular version) from pixie repo ? That introduces an additional requirement of being able to go to internet at the target machine ( where this installer runs ), but saves us the trouble to sync with official upstream manually

2022-12-24 02:25 UTC, abdullah-shah1 commented on src/pre-flight/px-preflight.sh
> +preFlight_checks() {
should we add all required tools checks here ?

2022-12-24 02:25 UTC, abdullah-shah1 commented on src/pre-flight/px-preflight.sh
> + |  __ (_)    (_)      |_   _|         | |      | | |
Not the Installer.

2022-12-24 06:46 UTC, sidra-xcbg commented on .github/workflows/linter.yml
> +    branches-ignore: [master, main]
ok will be fixed. was just to avoid a re-run since already run is established on pull-request in next line.

2022-12-24 06:50 UTC, sidra-xcbg commented on .github/workflows/linter.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Apparently created when we enable github actions on a repo. Details in https://docs.github.com/en/actions/security-guides/automatic-token-authentication

2022-12-24 06:51 UTC, sidra-xcbg commented on .github/workflows/shellcheck.yml
> +          scandir: './src'
that is our src folder we want scanned for bash scripts.

2022-12-27 07:51 UTC, yousaf-aftab commented on src/pre-flight/px-preflight.sh
> + |  __ (_)    (_)      |_   _|         | |      | | |
fixed in [3f2aa08](https://github.com/X-CBG/xk8s/commit/3f2aa08c4167f30a08093e7142710804b14c203c)

2022-12-27 10:13 UTC, yousaf-aftab commented on src/checker/px-checker.sh
> +    then
Encapsulated the pxNS checker using kubectl in else block.
Changes are fixed in [3c64725](https://github.com/X-CBG/xk8s/commit/3c64725a597e51a43b80a145eeac85fecdda04d1)

2022-12-27 12:37 UTC, alikhanxgrid commented on Makefile
> +clientCert = /home/noman/.minikube/profiles/minikube/client.crt
Will be resolved.

2022-12-28 05:33 UTC, yousaf-aftab commented on .github/workflows/linter.yml
> +    branches-ignore: [master, main]
fixed [48fc7a7](https://github.com/X-CBG/xk8s/pull/17/commits/48fc7a7bba1bfbad48f45c08ff79577334b0a87f)

2023-01-01 18:05 UTC, yousaf-aftab approved these changes

2023-01-02 09:43 UTC, closed without merging